# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Employee_overview.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Employees_Overview(object):
    def setupUi(self, Employees_Overview):
        Employees_Overview.setObjectName("Employees_Overview")
        Employees_Overview.resize(938, 650)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/gui_image/drop_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Employees_Overview.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Employees_Overview)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.GL_control = QtWidgets.QGridLayout()
        self.GL_control.setObjectName("GL_control")
        self.PB_drink = QtWidgets.QPushButton(self.centralwidget)
        self.PB_drink.setMinimumSize(QtCore.QSize(150, 0))
        self.PB_drink.setObjectName("PB_drink")
        self.GL_control.addWidget(self.PB_drink, 7, 1, 1, 1)
        self.LB_dehydration = QtWidgets.QLabel(self.centralwidget)
        self.LB_dehydration.setObjectName("LB_dehydration")
        self.GL_control.addWidget(self.LB_dehydration, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.LB_temperature_val = QtWidgets.QLabel(self.centralwidget)
        self.LB_temperature_val.setText("")
        self.LB_temperature_val.setObjectName("LB_temperature_val")
        self.GL_control.addWidget(self.LB_temperature_val, 4, 1, 1, 1)
        self.LB_Temperature = QtWidgets.QLabel(self.centralwidget)
        self.LB_Temperature.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LB_Temperature.setObjectName("LB_Temperature")
        self.GL_control.addWidget(self.LB_Temperature, 4, 0, 1, 1)
        self.TB_instruction = QtWidgets.QTextBrowser(self.centralwidget)
        self.TB_instruction.setMinimumSize(QtCore.QSize(0, 177))
        self.TB_instruction.setObjectName("TB_instruction")
        self.GL_control.addWidget(self.TB_instruction, 9, 0, 1, 2)
        self.LB_select = QtWidgets.QLabel(self.centralwidget)
        self.LB_select.setMaximumSize(QtCore.QSize(16777211, 16777215))
        self.LB_select.setObjectName("LB_select")
        self.GL_control.addWidget(self.LB_select, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.LB_select_val = QtWidgets.QLabel(self.centralwidget)
        self.LB_select_val.setText("")
        self.LB_select_val.setObjectName("LB_select_val")
        self.GL_control.addWidget(self.LB_select_val, 1, 1, 1, 1)
        self.LB_dehydration_val = QtWidgets.QLabel(self.centralwidget)
        self.LB_dehydration_val.setText("")
        self.LB_dehydration_val.setObjectName("LB_dehydration_val")
        self.GL_control.addWidget(self.LB_dehydration_val, 3, 1, 1, 1)
        self.PB_report = QtWidgets.QPushButton(self.centralwidget)
        self.PB_report.setMinimumSize(QtCore.QSize(150, 0))
        self.PB_report.setObjectName("PB_report")
        self.GL_control.addWidget(self.PB_report, 7, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PB_set_name = QtWidgets.QPushButton(self.centralwidget)
        self.PB_set_name.setObjectName("PB_set_name")
        self.horizontalLayout_4.addWidget(self.PB_set_name)
        self.LB_name = QtWidgets.QLabel(self.centralwidget)
        self.LB_name.setObjectName("LB_name")
        self.horizontalLayout_4.addWidget(self.LB_name)
        self.GL_control.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.LB_name_val = QtWidgets.QLabel(self.centralwidget)
        self.LB_name_val.setText("")
        self.LB_name_val.setObjectName("LB_name_val")
        self.GL_control.addWidget(self.LB_name_val, 2, 1, 1, 1)
        self.LB_status_val = QtWidgets.QLabel(self.centralwidget)
        self.LB_status_val.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LB_status_val.setObjectName("LB_status_val")
        self.GL_control.addWidget(self.LB_status_val, 0, 1, 1, 1)
        self.PB_notif_all = QtWidgets.QPushButton(self.centralwidget)
        self.PB_notif_all.setObjectName("PB_notif_all")
        self.GL_control.addWidget(self.PB_notif_all, 8, 0, 1, 2)
        self.LB_image = QtWidgets.QLabel(self.centralwidget)
        self.LB_image.setText("")
        self.LB_image.setPixmap(QtGui.QPixmap("../../../../../.designer/backup/water_bottle.jpg"))
        self.LB_image.setObjectName("LB_image")
        self.GL_control.addWidget(self.LB_image, 11, 0, 1, 2)
        self.PB_connect_nrf = QtWidgets.QPushButton(self.centralwidget)
        self.PB_connect_nrf.setObjectName("PB_connect_nrf")
        self.GL_control.addWidget(self.PB_connect_nrf, 0, 0, 1, 1)
        self.LB_humidity = QtWidgets.QLabel(self.centralwidget)
        self.LB_humidity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LB_humidity.setObjectName("LB_humidity")
        self.GL_control.addWidget(self.LB_humidity, 5, 0, 1, 1)
        self.LB_humidity_val = QtWidgets.QLabel(self.centralwidget)
        self.LB_humidity_val.setText("")
        self.LB_humidity_val.setObjectName("LB_humidity_val")
        self.GL_control.addWidget(self.LB_humidity_val, 5, 1, 1, 1)
        self.horizontalLayout.addLayout(self.GL_control)
        self.VL_employees = QtWidgets.QVBoxLayout()
        self.VL_employees.setObjectName("VL_employees")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PB_save = QtWidgets.QPushButton(self.centralwidget)
        self.PB_save.setObjectName("PB_save")
        self.horizontalLayout_3.addWidget(self.PB_save)
        self.PB_import = QtWidgets.QPushButton(self.centralwidget)
        self.PB_import.setObjectName("PB_import")
        self.horizontalLayout_3.addWidget(self.PB_import)
        self.VL_employees.addLayout(self.horizontalLayout_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.VL_employees.addWidget(self.label_2)
        self.SA_employees_list = QtWidgets.QScrollArea(self.centralwidget)
        self.SA_employees_list.setMinimumSize(QtCore.QSize(445, 0))
        self.SA_employees_list.setWidgetResizable(True)
        self.SA_employees_list.setObjectName("SA_employees_list")
        self.SAWidget_employee_list = QtWidgets.QWidget()
        self.SAWidget_employee_list.setGeometry(QtCore.QRect(0, 0, 559, 545))
        self.SAWidget_employee_list.setObjectName("SAWidget_employee_list")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SAWidget_employee_list)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.VGB_employees = QtWidgets.QGroupBox(self.SAWidget_employee_list)
        self.VGB_employees.setTitle("")
        self.VGB_employees.setObjectName("VGB_employees")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.VGB_employees)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3.addWidget(self.VGB_employees)
        self.RB_autoscroll = QtWidgets.QRadioButton(self.SAWidget_employee_list)
        self.RB_autoscroll.setObjectName("RB_autoscroll")
        self.verticalLayout_3.addWidget(self.RB_autoscroll)
        self.SA_employees_list.setWidget(self.SAWidget_employee_list)
        self.VL_employees.addWidget(self.SA_employees_list)
        self.horizontalLayout.addLayout(self.VL_employees)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        Employees_Overview.setCentralWidget(self.centralwidget)

        self.retranslateUi(Employees_Overview)
        QtCore.QMetaObject.connectSlotsByName(Employees_Overview)

    def retranslateUi(self, Employees_Overview):
        _translate = QtCore.QCoreApplication.translate
        Employees_Overview.setWindowTitle(_translate("Employees_Overview", "Employee Overview"))
        self.PB_drink.setText(_translate("Employees_Overview", "Notif Drink"))
        self.LB_dehydration.setText(_translate("Employees_Overview", "Skin Temperature: "))
        self.LB_Temperature.setText(_translate("Employees_Overview", "Ambiant Temperature: "))
        self.TB_instruction.setHtml(_translate("Employees_Overview", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>"))
        self.LB_select.setText(_translate("Employees_Overview", "Employee Selected: "))
        self.PB_report.setText(_translate("Employees_Overview", "Notify Above Employee"))
        self.PB_set_name.setText(_translate("Employees_Overview", "Edit Name"))
        self.LB_name.setText(_translate("Employees_Overview", "Name: "))
        self.LB_status_val.setText(_translate("Employees_Overview", "Status NRF"))
        self.PB_notif_all.setText(_translate("Employees_Overview", "Notify All Employees"))
        self.PB_connect_nrf.setText(_translate("Employees_Overview", "Connect Receiver"))
        self.LB_humidity.setText(_translate("Employees_Overview", "Ambiant Humidity: "))
        self.PB_save.setText(_translate("Employees_Overview", "Save list info as.."))
        self.PB_import.setText(_translate("Employees_Overview", "Import list info.."))
        self.label_2.setText(_translate("Employees_Overview", "Select an employee in the list bellow "))
        self.RB_autoscroll.setText(_translate("Employees_Overview", "Allow auto scroll (when an employee send a notification)"))

